const fnPath = 'packages/functions/src'
export const functions = {
  get_profile: `${fnPath}/user/index.profile`,
  get_reset_password_link: `${fnPath}/reset_password/index.handler`,
  get_plans: `${fnPath}/plans/index.handler`,
  get_plan: `${fnPath}/plans/index.getSinglePlan`,
  get_checkout_url: `${fnPath}/plans/subscribe.subscribe`,
  get_checkout_url_free_trial: `${fnPath}/plans/subscribe.subscribeToFreeTrial`,
  get_billing_link: `${fnPath}/user/index.billingLink`,
  post_subscribe: `${fnPath}/plans/subscribe.handler`,
  get_tests: `${fnPath}/list_tests/index.handler`,
  get_test: `${fnPath}/get_test/index.handler`,
  get_test_history: `${fnPath}/get_test/index.history`,
  get_load_test: `${fnPath}/load_test/index.handler`,
  get_load_demo_test: `${fnPath}/load_test/index.demoTestHandler`,
  get_test_result: `${fnPath}/result/index.handler`,
  post_stripe_webhook: `${fnPath}/webhooks/stripe.handler`,
  post_newsletter_signup: `${fnPath}/newsletter/index.signup`,
  post_newsletter_unsubscribe: `${fnPath}/newsletter/index.unsubscribe`,
  get_tips: `${fnPath}/personalised_tips/index.handler`,
  post_welcome_message: `${fnPath}/welcome_email/index.message`,
  post_contact_form: `${fnPath}/contact/index.message`,
  post_daily_recalls: `${fnPath}/daily_recalls/index.empty`,
  post_answer: `${fnPath}/submit_answer/index.handler`,
  submit_answer_queue: `${fnPath}/submit_answer_queue/index.handler`,
  submit_answer_ddl: `${fnPath}/submit_answer_queue/index.dd_handler`,
  post_add_user: `${fnPath}/add_user_to_mongodb/index.handler`
}
